name: AWS Deploy
on: push

env:
  AWS_ROLE_ARN: ${{ secrets.AWS_ROLE_TO_ASSUME }}

permissions:
  id-token: write
  contents: read
jobs:
  aws-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ap-northeast-1
      - run: aws sts get-caller-identity
